# path to the data directory
data_dir: ./data/XR_DICOM
out_dir: ./outputs

train_len: 0.7
val_len: 0.1
test_len: 0.2

num_workers: 4
batch_size: 32

network: vgg11
optimizer: adam
lr: 0.001

max_epochs: 120
metrics: [auroc, accuracy, precision, recall, f1score]
monitor_metric: [loss]