# path to the data directory
file_extension: dcm
data_dir: ./data/XR_DICOM
out_dir: ./outputs

train_len: 0.7
val_len: 0.1
test_len: 0.2

num_workers: 12
batch_size: 32

network: swinv2_tiny_window16_256.ms_in1k
optimizer: adam
lr: 0.001
use_pos_weight: true

max_epochs: 150
metrics: [averageprecision, f1score]
monitor_metric: f1score
patience: 30

logger: wandb