# path to the data directory
file_extension: dcm
data_dir: ./data/XR_DICOM
out_dir: ./outputs

n_splits: 5

num_workers: 11
batch_size: 32

network: resnet50
optimizer: adam
lr: 0.001
use_pos_weight: true

max_epochs: 50
metrics: [averageprecision, f1score, precision, recall]
monitor_metric: f1score

logger: wandb